spring:
  config:
    import: configtree:/workspace/secrets/*/
group:
  cutoff-checker:
    time: 1800
    initial-check-delay: 0
    check-interval: 157
  loader:
    enabled: true
    initial-group-delay: 0
    initial-group-size: 3
    periodic-group-addition-interval: 300
    periodic-group-addition-count: 1