spring:
  config:
    import: configtree:/workspace/secrets/*/
group:
  loader:
    enabled: true
    group-service-jobs:
      load-groups:
        initial-delay: 0
        fixed-delay: 300
        initial-group-count: 3
        fixed-group-addition-count: 1
      expire-groups:
        initial-delay: 0
        fixed-delay: 300
        group-lifetime: 1800
      load-members:
        initial-delay: 5
        fixed-delay: 60
        member-join-max-delay: 120