apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/group-service/k8s/base?ref=635f1e6d90a20304995f71fc63faf5d2406f894c

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: group-service-config

images:
- name: ghcr.io/grouphq/group-service
  newName: ghcr.io/grouphq/group-service
  newTag: 635f1e6d90a20304995f71fc63faf5d2406f894c

replicas:
- count: 1
  name: group-service

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
- path: patch-tracing.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
