apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/group-service/k8s/base?ref=3f1bcd4e431ff705a92e77e637051f70a81fc890

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: group-service-config

images:
- name: group-service
  newName: ghcr.io/grouphq/group-service
  newTag: 3f1bcd4e431ff705a92e77e637051f70a81fc890

replicas:
- count: 1
  name: group-service

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
- path: patch-tracing.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=group-service
    name: group-service
