apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
spec:
  template:
    spec:
      containers:
        - name: group-service
          resources:
            requests:
              cpu: "0.1"
              memory: 128Mi
            limits:
              cpu: "2"
              memory: 128Mi