apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
spec:
  template:
    spec:
      containers:
        - name: group-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: grouphq-postgres-group-credentials
        - name: rabbitmq-credentials-volume
          secret:
            secretName: grouphq-rabbitmq-credentials
