apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
spec:
  template:
    spec:
      containers:
        - name: group-service
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 30
            periodSeconds: 5