apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
spec:
  template:
    spec:
      containers:
        - name: group-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      imagePullSecrets:
        - name: ghcr-secret