apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-sync
spec:
  template:
    spec:
      containers:
        - name: group-sync
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
      imagePullSecrets:
        - name: ghcr-secret