apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/grouphq/edge-service/k8s?ref=main

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: edge-service-config

images:
  - name: edge-service
    newName: ghcr.io/grouphq/edge-service
    newTag: latest

replicas:
  - count: 1
    name: edge-service

patches:
  - path: patch-env.yml
    target:
      kind: Deployment
      name: edge-service
      labelSelector: "app=edge-service"
