apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/group-sync/k8s/base?ref=22ec68a79b4ef46c4ae7436db6d3e34b5b38137f

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: group-sync-config

images:
- name: ghcr.io/grouphq/group-sync
  newName: ghcr.io/grouphq/group-sync
  newTag: 22ec68a79b4ef46c4ae7436db6d3e34b5b38137f

replicas:
- count: 1
  name: group-sync

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-tracing.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
