apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/group-sync/k8s/base?ref=2c40419a8c77f649358c8cbb7d7c793d4cdaea08

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: group-sync-config

images:
- name: ghcr.io/grouphq/group-sync
  newName: ghcr.io/grouphq/group-sync
  newTag: 2c40419a8c77f649358c8cbb7d7c793d4cdaea08

replicas:
- count: 2
  name: group-sync

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-tracing.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
