apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/group-sync/k8s?ref=39d81039da6820dc9af05ab33222dbdded0a5610

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: group-sync-config

images:
- name: group-sync
  newName: ghcr.io/grouphq/group-sync
  newTag: 39d81039da6820dc9af05ab33222dbdded0a5610

replicas:
- count: 2
  name: group-sync

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=group-sync
    name: group-sync
