apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-sync
spec:
  template:
    spec:
      containers:
        - name: group-sync
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            failureThreshold: 1
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            failureThreshold: 25
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 30
            periodSeconds: 5