apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/edge-service/k8s?ref=6e81f4c47c2c2ccd57d8b91c14198114d6888355

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-service-config

images:
- name: edge-service
  newName: ghcr.io/grouphq/edge-service
  newTag: 03cc85b821c230709359bc668b46dc74673655cd

replicas:
- count: 2
  name: edge-service

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
