global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:4317']
  - job_name: 'edge-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'edge-service:9000' ]
  - job_name: 'group-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'group-service:9001' ]
  - job_name: 'group-sync'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'group-sync:9002' ]
  - job_name: 'config-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'config-service:8888' ]
