apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/edge-service/k8s?ref=eb76e6f215b219fbd65109c29edf691cf4e52589

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-service-config

images:
- name: edge-service
  newName: ghcr.io/grouphq/edge-service
  newTag: eb76e6f215b219fbd65109c29edf691cf4e52589

replicas:
- count: 1
  name: edge-service

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-ingress.yml
  target:
    kind: Ingress
    name: grouphq-ingress
- path: patch-tracing.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
