apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/edge-service/k8s?ref=82d2437c25ac998a3a07afe23218dda1d4e7d9eb

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-service-config

images:
- name: edge-service
  newName: ghcr.io/grouphq/edge-service
  newTag: 82d2437c25ac998a3a07afe23218dda1d4e7d9eb

replicas:
- count: 2
  name: edge-service

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
