apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/edge-service/k8s/base?ref=0805abc58cf0cb0074f90934a5ab74040ef254e1

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-service-config

images:
- name: ghcr.io/grouphq/edge-service
  newName: ghcr.io/grouphq/edge-service
  newTag: 0805abc58cf0cb0074f90934a5ab74040ef254e1

replicas:
- count: 1
  name: edge-service

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-ingress.yml
  target:
    kind: Ingress
    name: grouphq-ingress
- path: patch-tracing.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-probes.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
- path: patch-volumes.yml
  target:
    kind: Deployment
    labelSelector: app=edge-service
    name: edge-service
