apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/grouphq-ui/k8s/base?ref=20b98f313e323b4a12cedd620c9249abc6acd83c

configMapGenerator:
- behavior: replace
  files:
  - config.json
  name: grouphq-ui-config

images:
- name: grouphq-ui
  newName: ghcr.io/grouphq/grouphq-ui
  newTag: 20b98f313e323b4a12cedd620c9249abc6acd83c

replicas:
- count: 1
  name: grouphq-ui

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
