apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/grouphq-ui/k8s?ref=a34842be36ce310f6dbc83d234c82a38c233cc3b

configMapGenerator:
- behavior: replace
  files:
  - config.json
  name: grouphq-ui-config

images:
- name: ghcr.io/grouphq/grouphq-ui
  newName: ghcr.io/grouphq/grouphq-ui
  newTag: a34842be36ce310f6dbc83d234c82a38c233cc3b

replicas:
- count: 2
  name: grouphq-ui

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
