apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/grouphq-ui/k8s?ref=7942ea25503387c3bddc0336bd335ddeb5fc78a6

configMapGenerator:
- behavior: replace
  files:
  - config.json
  name: grouphq-ui-config

images:
- name: ghcr.io/grouphq/grouphq-ui
  newName: ghcr.io/grouphq/grouphq-ui
  newTag: 7942ea25503387c3bddc0336bd335ddeb5fc78a6

replicas:
- count: 2
  name: grouphq-ui

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
