apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/grouphq-ui/k8s?ref=abe5772cd96442d0ce845228edb3322267483b7f

configMapGenerator:
- behavior: replace
  files:
  - config.json
  name: grouphq-ui-config

images:
- name: ghcr.io/grouphq/grouphq-ui
  newTag: abe5772cd96442d0ce845228edb3322267483b7f

replicas:
- count: 1
  name: grouphq-ui

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
