apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/grouphq-ui/k8s?ref=d79e0885d56c80c0359b19e9a0dfe41795309a27

configMapGenerator:
- behavior: replace
  files:
  - config.json
  name: grouphq-ui-config

images:
- name: grouphq-ui
  newName: ghcr.io/grouphq/grouphq-ui
  newTag: d79e0885d56c80c0359b19e9a0dfe41795309a27

replicas:
- count: 1
  name: grouphq-ui

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
