apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/grouphq-ui/k8s?ref=eb458260e2a25147b09799be1ab55ff9776f9519

configMapGenerator:
- behavior: replace
  files:
  - config.json
  name: grouphq-ui-config

images:
- name: ghcr.io/grouphq/grouphq-ui
  newName: ghcr.io/grouphq/grouphq-ui
  newTag: eb458260e2a25147b09799be1ab55ff9776f9519

replicas:
- count: 2
  name: grouphq-ui

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
