apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/grouphq/grouphq-ui/k8s/base?ref=b639d6bf6c7f7815d1e9a716e67369bf642f5780

configMapGenerator:
- behavior: replace
  files:
  - config.json
  name: grouphq-ui-config

images:
- name: grouphq-ui
  newName: ghcr.io/grouphq/grouphq-ui
  newTag: b639d6bf6c7f7815d1e9a716e67369bf642f5780

replicas:
- count: 1
  name: grouphq-ui

patches:
- path: patch-env.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
- path: patch-resources.yml
  target:
    kind: Deployment
    labelSelector: app=grouphq-ui
    name: grouphq-ui
