apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: therealmohamedmohamed@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - selector: {}
        dns01:
          cloudflare:
            email: therealmohamedmohamed@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token